create table app_bootstrap_marker (
    id bigint generated by default as identity primary key,
    marker_key varchar(100) not null unique,
    marker_value varchar(255) not null,
    created_at timestamp not null default current_timestamp
);

insert into app_bootstrap_marker (marker_key, marker_value)
values ('schema_version', 'm1');

