create table page_preview_session (
    id bigint generated by default as identity primary key,
    requested_url varchar(2048) not null,
    final_url varchar(2048),
    page_title varchar(512),
    load_duration_ms bigint,
    screenshot_path varchar(2048),
    status varchar(32) not null,
    error_message varchar(2000),
    created_at timestamp not null default current_timestamp
);
