create table crawl_rule (
    id bigint generated by default as identity primary key,
    rule_name varchar(255) not null,
    source_preview_session_id bigint not null references page_preview_session(id),
    created_at timestamp not null default current_timestamp,
    updated_at timestamp not null default current_timestamp
);

create table crawl_rule_version (
    id bigint generated by default as identity primary key,
    rule_id bigint not null references crawl_rule(id),
    version_no int not null,
    status varchar(32) not null,
    source_preview_session_id bigint not null references page_preview_session(id),
    created_at timestamp not null default current_timestamp,
    constraint uq_crawl_rule_version unique (rule_id, version_no)
);

create table crawl_rule_field (
    id bigint generated by default as identity primary key,
    rule_version_id bigint not null references crawl_rule_version(id),
    field_name varchar(128) not null,
    field_type varchar(64) not null,
    selected_tag_name varchar(64) not null,
    selected_text varchar(2000) not null,
    dom_path varchar(2000) not null,
    created_at timestamp not null default current_timestamp
);

create table crawl_selector_candidate (
    id bigint generated by default as identity primary key,
    field_id bigint not null references crawl_rule_field(id),
    selector_type varchar(64) not null,
    selector_value varchar(2000) not null,
    priority int not null,
    created_at timestamp not null default current_timestamp
);
