create table rule_preview_run (
    id bigint generated by default as identity primary key,
    rule_version_id bigint not null references crawl_rule_version(id),
    preview_session_id bigint not null references page_preview_session(id),
    source_url varchar(2048) not null,
    created_at timestamp not null default current_timestamp
);

create table rule_preview_field_result (
    id bigint generated by default as identity primary key,
    preview_run_id bigint not null references rule_preview_run(id),
    field_id bigint not null references crawl_rule_field(id),
    selector_candidate_id bigint references crawl_selector_candidate(id),
    extracted_value varchar(4000),
    status varchar(32) not null,
    validation_message varchar(2000),
    created_at timestamp not null default current_timestamp
);
