create table article (
    id bigint generated by default as identity primary key,
    source_url varchar(2048) not null unique,
    title varchar(512),
    author varchar(255),
    published_at timestamp null,
    summary text,
    content text,
    cover_image varchar(2048),
    created_at timestamp not null default current_timestamp,
    updated_at timestamp not null default current_timestamp
);

create table rule_article_mapping (
    id bigint generated by default as identity primary key,
    rule_version_id bigint not null references crawl_rule_version(id),
    field_id bigint not null references crawl_rule_field(id),
    article_column varchar(64) not null,
    created_at timestamp not null default current_timestamp
);
