create table crawl_task (
    id bigint generated by default as identity primary key,
    task_name varchar(255) not null,
    url_template varchar(2048) not null,
    rule_version_id bigint not null references crawl_rule_version(id),
    cron_expression varchar(128) not null,
    status varchar(32) not null,
    created_at timestamp not null default current_timestamp,
    updated_at timestamp not null default current_timestamp
);

create table crawl_run_log (
    id bigint generated by default as identity primary key,
    task_id bigint not null references crawl_task(id),
    rule_version_id bigint not null references crawl_rule_version(id),
    status varchar(32) not null,
    source_url varchar(2048),
    duration_ms bigint,
    error_message varchar(2000),
    started_at timestamp,
    finished_at timestamp,
    created_at timestamp not null default current_timestamp
);

create table crawl_snapshot (
    id bigint generated by default as identity primary key,
    run_log_id bigint not null references crawl_run_log(id),
    snapshot_type varchar(64) not null,
    file_path varchar(2048) not null,
    created_at timestamp not null default current_timestamp
);
