alter table crawl_rule_field
    add column field_role varchar(64) not null default 'DETAIL';

create table list_discovery_run (
    id bigint generated by default as identity primary key,
    rule_version_id bigint not null references crawl_rule_version(id),
    source_url varchar(2048) not null,
    created_at timestamp not null default current_timestamp
);

create table list_discovery_item (
    id bigint generated by default as identity primary key,
    run_id bigint not null references list_discovery_run(id),
    item_index int not null,
    title_text varchar(2000),
    detail_url varchar(2048),
    time_text varchar(255),
    created_at timestamp not null default current_timestamp
);
